name: sitio_facil_backend
description: Backend API para o app Sítio Fácil
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mysql_client: ^0.0.27
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  mailer: ^6.2.1
